shared:
    image: node:8
jobs:
    SIMPLE:
        steps:
            - echo: echo test
        requires: [~pr, ~commit]
    PARALLEL1:
        steps:
            - set-label: |
                meta set label VERSION_3.0,VERSION_2.0,VERSION_1.0
                meta set tests.coverage 100 # this should be the coverage percentage number
                meta set tests.results 10/10 # this should be `pass_tests_number/total_tests_number`
                meta set tests.coverageUrl /test/coverageReport.html # this should be a relative path to a build artifact
                meta set tests.resultsUrl /test/testReport.html # this should be a relative path to a build artifact
            - echo: echo test
        requires: [SIMPLE]
    PARALLEL2:
        steps:
            - echo: echo test
            - status: |
                 meta set meta.status.findbugs '{"status":"FAILURE","message":"923 issues found. Previous count: 914 issues.","url":"http://findbugs.com"}'
                 meta set meta.status.coverage '{"status":"SUCCESS","message":"Coverage is above 80%."}'
        requires: [SIMPLE]
    JOIN:
        steps:
            - echo: echo test
        requires: [PARALLEL1, PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
    AFTER-FAIL:
        steps:
            - echo: echo test
        requires: [FAIL]
    STAGING:
        steps:
            - echo: echo test
        requires: [~pr:staging, ~commit:staging]
    AFTER-STAGING:
        steps:
            - echo: echo test
        requires: [STAGING]
    REGEX:
        steps:
            - echo: echo test
        requires: [~pr:/^.*$/, ~commit:/^.*$/]
    MASTER-PR:
        steps:
            - echo: echo test
        requires: [~pr:master]
    AFTER-MASTER-PR:
        steps:
            - echo: echo test
        requires: [MASTER-PR]
