shared:
    image: node:8
jobs:
    SIMPLE:
        steps:
            - echo: echo test
        requires: [~pr, ~commit]
    PARALLEL1:
        steps:
            - set-label: |
                meta set label VERSION_3.0
                meta set label VERSION_2.0
                meta set label VERSION_1.0
            - echo: echo test
        requires: [SIMPLE]
    PARALLEL2:
        steps:
            - echo: echo test
        requires: [SIMPLE]
    JOIN:
        steps:
            - echo: echo test
        requires: [PARALLEL1, PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
    AFTER-FAIL:
        steps:
            - echo: echo test
        requires: [FAIL]
    STAGING:
        steps:
            - echo: echo test
        requires: [~pr:staging, ~commit:staging]
    AFTER-STAGING:
        steps:
            - echo: echo test
        requires: [STAGING]
    REGEX:
        steps:
            - echo: echo test
        requires: [~pr:/^.*$/, ~commit:/^.*$/]
    MASTER-PR:
        steps:
            - echo: echo test
        requires: [~pr:master]
    AFTER-MASTER-PR:
        steps:
            - echo: echo test
        requires: [MASTER-PR]
