shared:
    image: node:8
jobs:
    SIMPLE:
        steps:
            - echo: echo test
        requires: [~pr, ~commit]
    CHANDRA:
        steps:
            - set-unstable: |
                if [ "$COVERAGE" -lt 95 ]
                    then curl -X PUT -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: application/json" -d '{"status": "UNSTABLE", "statusMessage": "this build is unstable"}' "${API_URL}/${SD_BUILD_ID}"
                fi
            - echo: echo "This build status is set as Unstable and will not trigger the next build"
        environment:
              COVERAGE: 90
              API_URL: http://10.0.0.44:9000/v4/builds
        requires:
            - ~commit
    PARALLEL1:
        steps:
            - set-label: |
                meta set label VERSION_3.0
            - set-coverage-and-test-results: |
                meta set tests.coverage 100 
                meta set tests.results 10/10 
                meta set tests.coverageUrl /test/coverageReport.html 
                meta set tests.resultsUrl /test/testReport.html 
            - echo: echo test
        requires: [SIMPLE]
    PARALLEL2:
        steps:
            - echo: echo test
            - comment: meta set meta.summary.coverage "Coverage increased by 15%"
            - status: |
                 meta set meta.status.findbugs '{"status":"FAILURE","message":"923 issues found. Previous count: 914 issues.","url":"http://findbugs.com"}'
                 meta set meta.status.coverage '{"status":"SUCCESS","message":"Coverage is above 80%."}'
        requires: [SIMPLE]
    JOIN:
        steps:
            - echo: echo test
        requires: [PARALLEL1, PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
    AFTER-FAIL:
        steps:
            - echo: echo test
        requires: [FAIL]
    STAGING:
        steps:
            - echo: echo test
        requires: [~pr:staging, ~commit:staging]
    AFTER-STAGING:
        steps:
            - echo: echo test
        requires: [STAGING]
    REGEX:
        steps:
            - echo: echo test
        requires: [~pr:/^.*$/, ~commit:/^.*$/]
    MASTER-PR:
        steps:
            - echo: echo test
        requires: [~pr:master]
    AFTER-MASTER-PR:
        steps:
            - echo: echo test
        requires: [MASTER-PR]
